import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],

  // Load .env from the REPO ROOT, not from app/.
  //
  // VITE_WEB3FORMS_ACCESS_KEY lives in ../.env and the contact form needs it
  // at build time. Without this, Vite looks only in app/, finds nothing, and
  // bakes `undefined` into the bundle — a form that fails at runtime with no
  // build-time complaint at all.
  //
  // Only VITE_-prefixed variables are ever exposed to the client, so widening
  // the search directory does not risk leaking anything else that lands there.
  envDir: '..',

  server: {
    proxy: {
      // The contact form posts to /api/enquiry, which is served by the
      // Cloudflare Worker (app/worker/index.js) — not by Vite. Proxying it
      // means `npm run dev` keeps hot reload while the form still works
      // end to end, provided `npm run dev:api` is running alongside.
      //
      // Without both running, submitting the form in dev returns Vite's
      // index.html instead of JSON and fails with a parse error.
      '/api': {
        target: 'http://127.0.0.1:8787',
        changeOrigin: false,
      },

      // The admin panel is generated by the Worker, not built by Vite, so it
      // has to be proxied too. Note the proxy preserves the localhost
      // hostname, which is what the Worker's dev-auth bypass keys off.
      '/admin': {
        target: 'http://127.0.0.1:8787',
        changeOrigin: false,
      },
    },
  },
});
